USE NELITO

DROP TABLE STUDENT

CREATE TABLE STUDENT(STUDIO INT, SNAME VARCHAR(20), MATHS INT, ENGLISH INT, SCIENCE INT, TOTAL INT, AVERAGE INT)

INSERT INTO STUDENT VALUES
(100,'AMAN',90,89,78,NULL,NULL),
(200,'RAJ',80,80,78,NULL,NULL),
(300,'GOPAL',50,89,78,NULL,NULL),
(400,'KRISHNA',90,89,78,NULL,NULL),
(500,'RAMESH',90,89,78,NULL,NULL)

SELECT * FROM STUDENT

-- TASK 1
UPDATE STUDENT SET TOTAL = MATHS + ENGLISH + SCIENCE

-- TASK 2
UPDATE STUDENT SET AVERAGE = TOTAL/3

-- TASK 3
SELECT * FROM STUDENT WHERE STUDENT.MATHS > 90

-- TASK 4
SELECT * FROM STUDENT WHERE SNAME LIKE 'R%'

-- TASK 5 : count
SELECT COUNT(*) 'STUDENT COUNT' FROM STUDENT WHERE AVERAGE > 70

-- TASK 6
SELECT * FROM STUDENT WHERE SNAME = 'GOPAL' OR SNAME ='RAJ'

-- TASK 7
SELECT * FROM STUDENT WHERE STUDIO = 100 OR STUDIO = 500

-- TASK 8
SELECT * FROM STUDENT WHERE MATHS>50 AND ENGLISH>50 AND SCIENCE>50

-- TASK 9
SELECT * FROM STUDENT WHERE AVERAGE<90

-- TASK 10
SELECT * FROM STUDENT WHERE MATHS IS NULL OR ENGLISH IS NULL AND SCIENCE IS NULL

SELECT * FROM STUDENT WHERE MATHS = NULL OR ENGLISH = NULL AND SCIENCE = NULL





