USE NELITO

SELECT * FROM EMPLOYEE

SELECT * FROM EMPLOYEE WHERE  NOT (EMPNAME = 'AKASH' OR EMPNAME ='SAKSHI');


--SELECT * FROM DEPTT

--
SELECT EMPNAME 'EMPLOYEE NAME' FROM EMPLOYEE 

SELECT DISTINCT DEPTID FROM EMPLOYEE

SELECT * FROM EMPLOYEE ORDER BY EMPNAME DESC

SELECT * FROM EMPLOYEE WHERE EMPNAME LIKE '%A%'

SELECT * FROM EMPLOYEE WHERE EMPNAME LIKE '%A'

SELECT * FROM EMPLOYEE WHERE EMPNAME LIKE '%H' AND EMPNAME LIKE '_____'

SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 1000 AND 5000

SELECT COUNT(*) SALES FROM EMPLOYEE WHERE DEPTID = 100

-- STRING FUNCTION
SELECT CHARINDEX('N','SANJAY')

SELECT LEFT('HITENDRA',5)

SELECT RIGHT('ASIF', 2)

SELECT RIGHT('MADHURA',2)

SELECT LOWER('HITENDRA')

SELECT UPPER('ASIF bihar')

SELECT 'ASHISH'+LTRIM('     BISWAS') -- LEFT TRIM

SELECT 'ASHISH'+'     BISWAS'

SELECT RTRIM('RAM     ')+'SITA' --RIGHT TRIM

SELECT ('RAM     ')+'SITA'

SELECT LEN('RAM AND SHYAM')

SELECT PATINDEX('%NITA%', 'VANITA')

SELECT REVERSE('SURAJ') + REVERSE('SHILA')

SELECT REVERSE('MADHURA')

SELECT 'SURESH'+'     '+'THANE'

SELECT 'RAM'+SPACE(10)+'SHYAM'

SELECT STR(123.6644477755,7,3)

SELECT STR(123.6644477755,9,4)--(No, Memory, After Decimal)

SELECT STR(123.6644477755,7,2)

SELECT STR(123.6644477755,7,4)

SELECT SUBSTRING('VINITA',2,4)

SELECT SUBSTRING('BHAGYASHREE',2,4)

SELECT SUBSTRING('CHAKRAPREMI',2,9)

DROP TABLE CUSTOMERS

CREATE TABLE CUSTOMERS (CONTACTNAME VARCHAR(30), ADDRESS VARCHAR(20), EMAIL VARCHAR(30))

INSERT INTO CUSTOMERS VALUES 
('SURESH ')

